### ISSUE TITLE
Release apks

### ISSUE THREAD

**Issue by cusspvz** [theksmith/CarBusInterface#11]
It would be nice to have release apk's on GH release tags info.

**Comment by theksmith** [comment]
i'm not sure i understand your request. the .apk's are for each version are in the "Recent Builds" folder (https://github.com/theksmith/CarBusInterface/tree/master/Recent%20Builds).

are you wanting non-debug compiled versions or ?

**Comment by cusspvz** [comment]
Oh, I see. Usually on GitHub, people let their builds out of the git folders and place them on each [release tag](https://github.com/theksmith/CarBusInterface/releases).

I'm anxiously waiting for my ELM327 to arrive for testing this up. :D
