### ISSUE TITLE
Increase android:versionCode

### ISSUE THREAD

**Issue by krt16s** [theksmith/CarBusInterface#2]
The android:versionCode is an integer that get's checked when an app checks for updates. Your verion "name" gets bumped, but for Android this is just renaming an already delpoyed verison, namely versionCode 1. Update this integer with every release.

**Comment by theksmith** [comment]
originally i was doing this since i considered everything pre 1.0 to be "beta", so it would deploy over top of itself without any hassle each time but i went ahead and fixed this in the latest version (v0.9) (which is now build 90, v1.0 would be build 100, v1.1 will be build 110 etc.)
